version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexthire-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=mongodb+srv://demo:demo@cluster0.mongodb.net/nexthire_db
      - JWT_SECRET=nexthire_super_secret_jwt_key_2026
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
